theme: jekyll-theme-minimal
title: Nym # "\u2009" # Unicode "Thin Space" character # Making cities that work # Nym Cities # 
logo: /flying_pig.svg
description: "\u2009" # Unicode "Thin Space" character
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
